-- MySQL Script generated by MySQL Workbench
-- 04/08/16 22:27:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema helios_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `helios_db` ;

-- -----------------------------------------------------
-- Schema helios_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `helios_db` ;
USE `helios_db` ;

-- -----------------------------------------------------
-- Table `helios_db`.`errorCodes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helios_db`.`errorCodes` (
  `id` SMALLINT NULL DEFAULT NULL,
  `type` TINYTEXT NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `helios_db`.`repeatingSchedEvents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helios_db`.`repeatingSchedEvents` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `group_id` INT NULL,
  `start` DATETIME NOT NULL,
  `end` DATETIME NOT NULL,
  `period` INT NOT NULL,
  `name` TINYTEXT NOT NULL,
  `comment` TEXT NULL DEFAULT NULL,
  `topic` TEXT NOT NULL,
  `command` TEXT NULL DEFAULT NULL,
  `arguments` TEXT NULL DEFAULT NULL,
  `executed` TINYINT NOT NULL DEFAULT False,
  `deleted` TINYINT NOT NULL DEFAULT False,
  PRIMARY KEY (`id`),
  INDEX (`executed` ASC),
  INDEX (`deleted` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `group_id_UNIQUE` (`group_id` ASC),
  CONSTRAINT ``
    FOREIGN KEY (`executed`)
    REFERENCES `helios_db`.`errorCodes` (`id`),
  CONSTRAINT ``
    FOREIGN KEY (`deleted`)
    REFERENCES `helios_db`.`errorCodes` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `helios_db`.`schedEvents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helios_db`.`schedEvents` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `group_id` INT NULL DEFAULT NULL,
  `time` DATETIME NOT NULL,
  `name` TINYTEXT NOT NULL,
  `comment` TEXT NULL DEFAULT NULL,
  `topic` TEXT NOT NULL,
  `command` TEXT NULL DEFAULT NULL,
  `arguments` TEXT NULL DEFAULT NULL,
  `executed` TINYINT NOT NULL DEFAULT false,
  `deleted` TINYINT NOT NULL DEFAULT false,
  PRIMARY KEY (`id`),
  INDEX (`group_id` ASC),
  INDEX (`executed` ASC),
  INDEX (`deleted` ASC),
  CONSTRAINT ``
    FOREIGN KEY (`group_id`)
    REFERENCES `helios_db`.`repeatingSchedEvents` (`id`),
  CONSTRAINT ``
    FOREIGN KEY (`executed`)
    REFERENCES `helios_db`.`errorCodes` (`id`),
  CONSTRAINT ``
    FOREIGN KEY (`deleted`)
    REFERENCES `helios_db`.`errorCodes` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `helios_db`.`subsciberSetup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helios_db`.`subsciberSetup` (
  `mac_addr` BIGINT UNSIGNED NOT NULL,
  `topic` TEXT NOT NULL,
  `setup_string` TEXT NULL,
  `id` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `helios_db`.`eventsRecord`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helios_db`.`eventsRecord` (
  `time` DATETIME NULL DEFAULT NULL,
  `topic` TEXT NULL DEFAULT NULL,
  `message` TEXT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `helios_db`.`currentRecordInstant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helios_db`.`currentRecordInstant` (
  `sensor_id` TINYINT UNSIGNED NULL DEFAULT NULL,
  `time` DATETIME NULL DEFAULT NULL,
  `value` FLOAT(7,3) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `helios_db`.`currentRecordHourly`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helios_db`.`currentRecordHourly` (
  `sensor_id` TINYINT UNSIGNED NULL DEFAULT NULL,
  `time` DATETIME NULL DEFAULT NULL,
  `value` FLOAT(7,3) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `helios_db`.`lastCurrentRecord`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helios_db`.`lastCurrentRecord` (
  `sensor_id` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `time` DATETIME NULL DEFAULT NULL,
  `value` FLOAT(7,3) NULL DEFAULT NULL,
  PRIMARY KEY (`sensor_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `helios_db`.`notifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helios_db`.`notifications` (
  `type` TINYTEXT NULL DEFAULT NULL,
  `level` TINYINT NULL DEFAULT NULL,
  `time` DATETIME NULL DEFAULT NULL,
  `message` TEXT NULL DEFAULT NULL,
  INDEX (`level` ASC),
  CONSTRAINT ``
    FOREIGN KEY (`level`)
    REFERENCES `helios_db`.`errorCodes` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
